apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer # pvc를 사용하는 pod가 생길때까지 대기
